services:
  db:
    image: mysql:8.0
    container_name: mysql_vitalapp
    environment:
      MYSQL_ROOT_PASSWORD: saludvitalpro
      MYSQL_DATABASE: vitalapp
      MYSQL_USER: custom_user
      MYSQL_PASSWORD: saludvitalpro
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - vitalapp_network

  app:
    build:
      context: .
    container_name: vitalapp
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - vitalapp_network

  tests:
      build:
        context: .
      container_name: vitalapp_tests
      command: ["test"]
      depends_on:
        - db
      networks:
        - vitalapp_network

volumes:
  db_data:

networks:
  vitalapp_network:
    driver: bridge