name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: saludvitalpro
          MYSQL_DATABASE: vitalapp
          MYSQL_USER: custom_user
          MYSQL_PASSWORD: saludvitalpro
        options: >-
          --health-cmd="mysqladmin ping -h localhost --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
        # volumes:
        #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..60}; do
            echo "Checking MySQL connection..."
            if mysqladmin ping -h 127.0.0.1 --silent; then
              echo "✅ MySQL is ready."
              break
            fi
            echo "❌ MySQL not ready. Retrying..."
            sleep 5
          done

      - name: Test database connection
        run: |
          echo "Testing connection to MySQL..."
          mysql -h 127.0.0.1 -u custom_user -psaludvitalpro -e "CREATE DATABASE IF NOT EXISTS test_db; SHOW DATABASES; DROP DATABASE test_db;"
          echo "✅ Connection successful."

      - name: Check MySQL logs
        run: docker logs $(docker ps -q --filter "ancestor=mysql:8.0")

      - name: Inspect MySQL container health
        run: docker inspect --format='{{json .State.Health}}' $(docker ps -q --filter "ancestor=mysql:8.0")

      - name: Run tests
        env:
          SPRING_PROFILES_ACTIVE: test
        run: mvn test
